apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-smb-retain
  annotations:
provisioner: csi.san.synology.com
# if all params are empty, synology CSI will choose an available location to create volume
parameters:
  dsm: '192.168.50.127'
  location: '/volume1'
  # csi.storage.k8s.io/node-stage-secret-name: cifs-csi-credentials
  # csi.storage.k8s.io/node-stage-secret-namespace: synology-csi
  protocol: smb
  csi.storage.k8s.io/fsType: 'ext4'
reclaimPolicy: Retain
allowVolumeExpansion: true
