apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi.san.synology.com
# if all params are empty, synology CSI will choose an available location to create volume
parameters:
  dsm: '192.168.50.127'
  location: '/k8s-synology'
  type: 'thin'
  protocol: iscsi
  csi.storage.k8s.io/fstype: 'ext4'
reclaimPolicy: Delete
allowVolumeExpansion: true
