apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uJ7ZVWwCo2r0/S1VQ9UqoeIVxrWZn3rEia0vnqizd3M5cmNnAHYq+MxOGzkStzS+leSoQI6/FVwTZo1G0wf35uKQPViRkrUlbO4kaV142oF5VYKGieR90dF1/uBPb72vojYw3PsagnWJaytO18iwSwaTJHwNxkl9RQOJ7EOjQhJQs56loiMuYS+b7ldLACn2lKUHNbIbg7DGljrTt4xFrBpj4IQ9F8rAf80gKJ6hC83Xz8kB+VNFTQ==,iv:IWVXnQ0NuohxjEVmFmBcLaigkMdpzAv3KlqMArWWojg=,tag:mVWdl4Y/CvPV47paU6GxCg==,type:comment]
    #ENC[AES256_GCM,data:L9m6h9Ntimr+KkEb4ZqTmI7Te57R/bmetfsemuw3DwdFCEoHo6cgFkVD2RShOUnjZdCrRic=,iv:YWhF4JjxCms+TI1A0iY15Bi+DkRmKafU3B8xSYxUR78=,tag:tD/jKyzmv2O4jLIPAHvqTw==,type:comment]
    #ENC[AES256_GCM,data:cLE3HdNyTN3cL3NrtR1SQaVw+JqIvTiySNrBq8RW4YRrhrS6CcUmkACd4bF3xyy/3ve/cvm3t1C+1INL7gsZ8+Jv+qSk6g==,iv:nLoBfqByhZLVOAW09BlJ2oXDIePSKZQxndRCm7EPXqs=,tag:q09twHffOzbjSNTWSSd1aQ==,type:comment]
    #ENC[AES256_GCM,data:IRmuVBoG/IRYenDA84Makg0RkQosEeaWS3wnHwJZzK1ra8QkfU60eobtikDGjFCPlpl/uzCZaT52E9m63iuK9+sd7z2WzCc=,iv:UujHEE2EC0MVv9KAAj/14vWxcikvqZnwnyP8LNZ6m0I=,tag:yE6by82VUp2WLFM7sc80Mg==,type:comment]
    #ENC[AES256_GCM,data:zX/e0X7TILJMfhKRvh9XDkHYb/heDbsCvroJyYmSIfdFaaan4ixO7IriSR3C41Js7Fgy+y0zxdqQIU1PiMjXIBw=,iv:COIx7nv2O7XZvGtzHVn+v1Kv0u0PZCmBMnEACzGfd1s=,tag:z8i4fHuXv6Y0RP0Uc1Ry3A==,type:comment]
    #ENC[AES256_GCM,data:b6zE/1oV0B8EjMcVAOtxQAFuYz2XsUdf3HAgnvoLlJYDgLqhPuwMR9c+xNqzN8MJAzmBwamUbP5oWfJd9hfH,iv:QuRJdnr/TUNbXHpdGfq20JXeAgg9eGcFEz1D3qGDVpI=,tag:dmqU3kChgvYqLxfIvQzQJg==,type:comment]
    #ENC[AES256_GCM,data:jORUdfuF/Nq4xro+YL4lRPCGqIfL8PkXXZRmMXobnKKyhNrIBG2eJ/5nJicN3tSCzMc/jed+GhSOnEc67Do0A1oN/ThFSrQkYBPUv9tz4KAlyR1f5I/0mXPavMPz374o2fhlFVOL6UjmC4RJchi4W4BWgTTFUFPBNnQlyZLETgn6sPA/60a59GL1eTf31TlmNT8QQnKb+bf4sPG/UHnlBvBbibFscEHYNmuWtDsIBGMLPzjkXBYQEA==,iv:eCU0cBHUPKEwi2bCQGb2LXOCqj7WeDmQ+EnQCLEcsx4=,tag:9B1+Wr67yAPRRD2TdyoFKA==,type:comment]
    client_id: ENC[AES256_GCM,data:vKm/Ns/ozIPFIyXvUYlfXRg=,iv:9rz/u+xDOjBf8WzYSskGVk51ArdBjTllw4Vgx02Vdu8=,tag:98qNclJ0xmtNwiVVH5pEAg==,type:str]
    client_secret: ENC[AES256_GCM,data:65qjGqFVHm8JTo4DzpjV9BTVjKktyo9jp6r9IBuK1sT+iTwkfyipGxZXaOhh/ieepYbdvleAe+jeOVl9DUBzkw==,iv:YF8fnP4uOx8zeg3h2oiibNqHFZJYniAaNPGoQvijd00=,tag:aUydal1zySFHYDUCSiNrvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBublBhRWdFdjBxLzA4M3Nx
            WWwvaFpmeGwrS2VvNDExaVhvd1JIZk9YWkY4CitnS1hBL1Vqa3Ryb0pJQlY5T1Nq
            OE85N3U2c0lFejZjempNQ00xRDhha3cKLS0tIHprTjVNaUE2LzM2UmY3YyttU1lp
            TlNvZndDMi8zT0RvaGpXekRaQkNQUjgKtFK10JlvzEG548OirV99oxlp47GKESkz
            zJGYAlEx/0570ZsUR+k89ILordY1ZWf+k2GC25SvqtliFJ+KV+yCHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T06:09:35Z"
    mac: ENC[AES256_GCM,data:gBNf6zZRQvewpsEAXapIFxUzbsxt3htd68BsEm4fCxQHV4PtStKJ0BGWSU2mlBwIieAMMAhKTsRUgXTU1Mv+Jm5mHpNt0TXIf+GaAcqilfJ9r4Ga59GSRRKRovNZYeM0rTP9W2IPSnSjLaZnxAIlacvxXooQDSMRP/b9+P5QVFo=,iv:vuA5vq9B7n4Rcsa4COT750bK4mEz6iC9ujfTtCHffLg=,tag:KwyJNbFFkpUQPI08GHZXRw==,type:str]
    version: 3.13.2
