apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:LsKSyypUNPhSLYJkGKO8NYA/Mab5eeHl4DKzJ6MihQ==,iv:tpQ8uS1jf5lzZ6hQ3W2otFLhflDtxchSxenMoepOxUo=,tag:Y/PBTLx6xz7KB714S6aLOw==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:W1EYAhQZVkpMcFE94KnnvqZCPpv26J2lzv/KhDuloiHOuz2E,iv:u7xMtxjnHyYF2gin5dSmQEUci4RJ+tzMBtIRkj/tITo=,tag:mg5OywZFTUUelhedLSN/hg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:Cb7K24UkYOo=,iv:2/ZPYwQbpWnjguXfWRwT60ibrlfgnXMxcLP5cGBRFyI=,tag:js2yhe6J/IgRL+COChg7ag==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:NbelGOVPxh4PcHsf9RVmityfakaSaQ==,iv:NBqGcf8ou7fOGbCkZy1ulirCXvii0QlFuzFcaFBhQXc=,tag:ePzgSj6pC5yMJqKXz5mWrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOEdjK0tZZVRxWDlRenp0
            ZC8vOG5zOVRQTlhGVEtJQXhhdzJWVCtLaUNzCmlWSW45WHZoVFMrcjBNRllEUEVM
            OTEwZ3BSNlVETHdyMmdaL2wwSDJoMUkKLS0tIC9tZlZwb1JtNGk2VkRpOWtYb0l3
            QVA1ck9WTDlpRm9WWi83VW9DMnhNT3cKhl4izXSPuduM2QqHCzuH6ScWx9pZln8t
            2bELo8D2Sw/MlmmN9AskLjJqHWp//wbqxS+WXXRCND6vBy8JshP5IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T13:38:12Z"
    mac: ENC[AES256_GCM,data:eRo+B+pEMNSg3HlYhu/jSAdtyTSxBVynzbsImcKQXsmZgE8HXYKw8xeTkNMTkNXwCr/fkU1SA+S2auherM/B9O9oC5EO4fvZmel0dUOgd+8W9Vzu4Ebd1fHy8LM6G5IUBE1GCNpPGaNxIwINdcLHiBrZeG4Qmu222582JQTsHpA=,iv:nkwcvsVLCABWarM4MZplfZZ+uWbGkjI2b92jB/q8lxE=,tag:pz28Bw/ig/oyF+m+r9gZAg==,type:str]
    version: 3.13.2
