apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:LsKSyypUNPhSLYJkGKO8NYA/Mab5eeHl4DKzJ6MihQ==,iv:tpQ8uS1jf5lzZ6hQ3W2otFLhflDtxchSxenMoepOxUo=,tag:Y/PBTLx6xz7KB714S6aLOw==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:W1EYAhQZVkpMcFE94KnnvqZCPpv26J2lzv/KhDuloiHOuz2E,iv:u7xMtxjnHyYF2gin5dSmQEUci4RJ+tzMBtIRkj/tITo=,tag:mg5OywZFTUUelhedLSN/hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOEdjK0tZZVRxWDlRenp0
            ZC8vOG5zOVRQTlhGVEtJQXhhdzJWVCtLaUNzCmlWSW45WHZoVFMrcjBNRllEUEVM
            OTEwZ3BSNlVETHdyMmdaL2wwSDJoMUkKLS0tIC9tZlZwb1JtNGk2VkRpOWtYb0l3
            QVA1ck9WTDlpRm9WWi83VW9DMnhNT3cKhl4izXSPuduM2QqHCzuH6ScWx9pZln8t
            2bELo8D2Sw/MlmmN9AskLjJqHWp//wbqxS+WXXRCND6vBy8JshP5IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T01:05:35Z"
    mac: ENC[AES256_GCM,data:2BeP3BqGtp6ytxy1MlFapIw82K0MLrxFIBsk1jDrBB/Xlst5+9BK8v/v22Rv2oFMyiXP94Rke0zCIjh6i8qZQxbiEx8eoiAFsE6ZeYCPv9mzTEXMwsVC1R+2c/m62Hj+KbCuGr3PaOPl3eZxJuFTycojGUMtobEeaIXJnWiRyck=,iv:7MeJTUmD3CblP5zVdIc9FsgF74jOOEchzX+4VTiG7pk=,tag:bcDZ5etgmu+LXVc4t56P2g==,type:str]
    version: 3.13.2
