apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:8dv3MJxQTIopEVwe+zCiP6eLw3yM/ACVSXTHWQEgHw==,iv:P3dAz5vFGSqtKPhZUJX5RItF7NxH5jb5b94ITbye9H8=,tag:YqFLGMqdfsUAeUqQWUEufg==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:7mN2gCF1yhc69iN8auNuvjVImGxCYygc87h9gofHiz0S/YW3,iv:KFElpUDWssVz9l5imyFkMrtH6P0ScEl/UcmalxQIu+I=,tag:u/PqcPIyKgPMasnGT3R0gA==,type:str]
    HOMEPAGE_VAR_CF_API_TOKEN: ENC[AES256_GCM,data:7razt7sbJEnQN6urI6DkhHhkoyotp/1N0h6nOEWJ8H9pontdvfB+ivcd6ebpPZJXmoxX5UM=,iv:3v10pNSNLLd5XOrXUXRAZoOYC/dJicBLRDgaJ3McdWQ=,tag:dRSysj6r/9QwIHqbt8yWag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV3NIbEpYN3AwcWtqWFJ3
            dWJrTXJZWHZmSjBNZjJ2T25TcjBneDNNR0Q0Cm54dHdqV2N6dmREdDRuQWVDSm9y
            dlpxUDFvZGE1M0ErQk5BM0hXY05lSW8KLS0tIE05TCt1aHhnSkcwa0dkL3NKdTlt
            WVJQT2hmOFFFdEM5bmQ5UkFuV3gwdWcKZSUy0IhcFQC7jwNgkNx9xx800mO1whLV
            ob4V6ADOzmLZKhXxkUWNxW0NFDnfHmLud/WIlL9Qqsy1OPqlDjBLzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T14:24:56Z"
    mac: ENC[AES256_GCM,data:jh/dm4i7wIaYfUJfYnRb2TQyI2gOKCiwunst1tiT39s29pxUeNsuI0dgodWteBedslLMRNlmiVQ+onQfuXXxnwRH2i9tpW+vldkGWZwx5WdGSSe7dTNjFKd18psg+jEk7dQpwLyrIpMoMB/DQEG/jGT8KpH/SJqk2celdT4jUMI=,iv:wPyrUJ0mlPx4IMOzmIQAb4Abw3PqVgoqK1cyFBb5Xlg=,tag:77dSHmZfQGTOj4RAWItU8g==,type:str]
    version: 3.13.2
