apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-synology
  namespace: mealie
spec:
  storageClassName: "synology-iscsi-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
