apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: gatus
type: Opaque
stringData:
    GATUS_NTFY_TOPIC: ENC[AES256_GCM,data:h7vFOlVQtdgLY0PJpQoj30Dv+8phefsdSjNSLFoMXYg=,iv:KTQIstr7q+tdKk9GveOwC5EWvMLCn/oBqmLCDCiIOAw=,tag:uPPWdkujo4vtmDmx5TxaeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUmtibmp0L2R4NzlZYmln
            WmpmbkF0ODlTQ21wNU1zWE1GZWkxa3FMSHc4CmRzcHorNk5SYVR0c1ZzUnFrTURz
            NytBNmp5bEJlalcvTGlaYWR1Q3ovdk0KLS0tIDZhZlJBUmVaTWp0LzFucmVFZUtS
            NncxTE5rbEVvZVBNTzVZZjBvbEp4d0kKiPI9+SKeVGIh9UwckuyMXY6IgvpiAHVd
            cR9khmFfAjQpAYsGHmyi+v1dRghgFSw5EphzKSuptVittgkZffPvXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T09:14:18Z"
    mac: ENC[AES256_GCM,data:5KgPAekPIslr7/Bq6YElfAOHf8VCdWfk4u56Ha7jKh571XjD3cwabh4wb4QZGgscbsWwCxpVRK+Z6bn5DRtiAOUpbOf+MeuhHKV9DERxWcYMXTUwtL3bJf8/9GmwGI5LYL1e3f65dEe2oJI8svLTYLGN+raIGVs8RJuLAraMWJE=,iv:e4LcSS2aKIsX58ZVGCBaG0NQrblfpMo2uWy7C/YKkvw=,tag:ZwYV3rYrAJjG2eLCGsNcFQ==,type:str]
    version: 3.13.2
