apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: health
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:7v76rrE=,iv:2nVYWgxPlDspZ3o9N0PgRy5XOfOp9AgaHMCbyzrz3TA=,tag:F1dcaIkqAMNUEwH5si+RYg==,type:str]
    admin-password: ENC[AES256_GCM,data:V1AtvRGGZ94HbbfGSTOIDEaB9ovmxQi1eIaPYQ==,iv:/aigRT+tKGl15X7a9NkAFhCDvATFm8jDvCYWBzwWzMU=,tag:6WjbZxLA4SaLm8NPxuxUxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQVRhWUZrb2lURzN1TEps
            eC9LTm5KTHJFNkNQcDVkRFlXMlhxM2NPTEFvCnRYYzhIUTBkaEM1T3FuL0RyY0tY
            NXdHbTN0K3Z5WXVtMUQ0cllZRzBlWGcKLS0tIHBGRFpBdWE5Q3R4SU56RHZ5SWNq
            eCtIby93R0tRY3c4Y04zdW5xSTlOU0kKCD/AWg+AY3u7X65mMj9ailMTi5UgcBwl
            eNpUkhx7dFebX++qJGzmq4I1g9WzKkeOLdbhxcuNY9+G5ADz5+9x1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T12:36:43Z"
    mac: ENC[AES256_GCM,data:gImpP/phdTnrLywZxPalQrZ9//cBvAWcznic4HCNkseyGbQNip+agT7qojrLyH6b4SC2njtNwvbg/UNyzFBB0xNBVDtwy+QwJs1Oak1Uuei/fsbPY6Rc4jXTTUWwpn7IjAPdz9D7Hmt3UOfli2TpY3ZZG1CpuqK9AdLx7WUeT0s=,iv:1gbVKAwKjW/KjQunyv9wXD/zbvLugFWioiEtvGYeemM=,tag:7bO9dyvFDZNs01E0OvaQvA==,type:str]
    version: 3.13.2
