apiVersion: v1
kind: Secret
metadata:
    name: pg-qs-writer
    namespace: health
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:cvva0IZ9+10o,iv:uWBwwSx3KvWDlnF0ERarqCUisoxdVMlm5r1a0MoggDM=,tag:fMVTqiZrWuujzLLeXApM9Q==,type:str]
    password: ENC[AES256_GCM,data:A/EsCXwP9aBp/SzAcyPRIXRQwRX0LilDvlJ1JpCIA6w=,iv:lg4rAyWb+IJ6XBb1hAj4gkGvMHLHRjr21l23EZsLEAQ=,tag:SaqzC9s5h2CiXlAq5jdsMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RW9DcHllZHFOVjArOFA3
            SzNxTVBsR2hMYk1hOCtkaThyczEzUWxKekJrCkdMUEpPVmRiWXd1MHU1VDV1RjRO
            TWpQL2xHRHNBR3kxUlk2bHh3Q0NFTXMKLS0tIDdhbkFzYXRwOHo4V2k2TTFyMkRJ
            cDlhdFdYM1Z6TlpHUnBSdS9FZnRqd0kKJHofqR/LoQKN1B4gTP6QzasegT1ZkAOZ
            mYedErP/rPGThO3iYh5+acdbYBGRPVnHirzERueLy5PPqU8bC1UpCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T09:41:17Z"
    mac: ENC[AES256_GCM,data:LU/Fnn4ziSkb5JM9cVNQfZmGh9du8VCbSaOm01iggiylrWkJYKKd8DGAePK1ZckGkDRkbByQJ+rdAFjIvFuslMLdEV3Inq9kCtGJfSWhueoa9HLi+l/goFcCFgY3V605YEbPnYk95wXah0baK/vqx5KRgNfbQIdtJEgJGYJiL7Q=,iv:3+KzlQN5nVcOxA+OeZGVSxryWrn5NDGCV68sics/o3g=,tag:H2YPNH1/gkelgUw0e0qaCw==,type:str]
    version: 3.13.2
