apiVersion: v1
kind: Secret
metadata:
    name: pg-qs-reader
    namespace: health
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:YyWLF7bUtIty,iv:OYMYOGBV7FZu3Lkd9L/khw9C8sgrBruouxPqqo0flwg=,tag:UWhLE0wt04GHH8tMqoEJuQ==,type:str]
    password: ENC[AES256_GCM,data:I1MD2Tq9+lJ++O/H04eXGIUcJG9AvNw9hIYyfX/gc6s=,iv:MOmv8rthXTbNgWeYInwMkxfdC5kDFrVrpHxniHYmmnw=,tag:XbmpjsCabhXzKWMODdWHDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MWhURk1JWE5MRE4vOUhX
            T2dlcDZIRlFjL3NNQ295dks5MzVKOGJCK3hjClBIZDFiWDVXalJPNXhZZHpiVk96
            RG5sRkhjWVNTQ242R1luM09mbm1RYjAKLS0tIDZmRDUyVzRZMzZMVEtWNmZTQ0o4
            ak9laml6OXRUa2dlMjRwVlo2UVNvdDQKqzKeLkWTvBjPl8zwLsGXQs0dXPTsuBNt
            HXndFNBjDMtPOWlHGeC73PNvPVYr6oXqxHvy0AidKNbkxNaaRRGsqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T09:41:17Z"
    mac: ENC[AES256_GCM,data:lkKuIpb1qZnKhyIfaPyDsNITr/3Tt+lnOBqPnk9OUjE03phC/FkywN8CIkkc10oPxMe3pgVM/PeaaT1Ti01oqkjYPiFRR/Xf/rLCyIjleO2p+9brcl3J4ItNBrsfSDQuU1CfEZHSiKLABaMyJ95jCgHT58iOhH0DPl8Y1xqW9y8=,iv:BVnte3KU6aCBWY0vkY1SA6lxSowo3dWppKvqD81GXxc=,tag:NQN6Zqz7rnevYGuIj3nzcQ==,type:str]
    version: 3.13.2
