apiVersion: v1
kind: Secret
metadata:
    name: withings-app
    namespace: health
type: Opaque
stringData:
    WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:aKbgu92qHJYeCgBupDtB+FwWzsJT9UtbpvBQ7fDvyEbkUv1h8Npf7fmB9K+/guUOnQsNNv0IqRNOBxegnygG2w==,iv:LQ784oFmNehPBz4SGxCt2Abtapvn3kPni2qOi+xoGMA=,tag:vSUuO/X3DSuJlDkOIy+x6Q==,type:str]
    WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:npIWUcqFLgFS5gjcEpEBEjU+fPREM5QDFnlQjzI5+tDDODRnNwT4jHOA8HJK/ek5HYKs0NKqKhSjEmWLYB9qqg==,iv:a3IJ8//X/Cd90on/GG9wqNn1eISO4dy1d0XGm1hwuf8=,tag:LOZRzOaZIsGnKfNT0mQPJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYUNIMnArOWplZGREQ0Mz
            SUFyQy8yTGtEZmVoWFhtQVBGNmhaa2d6VmpnCkZIN25Zck5BVk80RitmcVgyTDc2
            VzYyUXEvQkNqbUtaUFBoWXFzQ2JXSU0KLS0tIGpXTHM4SDloWDJaMDVrN2w0R002
            S2R4TmVPZDZjZG8vQkkzWlRGRGVYdkEKX7jMuKUxAUxMW3pSY3tVAIKC4INTuEFl
            CcCwqYQEvw+k10KSM3yHtJF5l5FnXoqjuz58IfC+363z+WF4vCiNYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T11:29:37Z"
    mac: ENC[AES256_GCM,data:cUp0VreIhGb78vEduN9NJaUtRA5M/piaIwSDCElH6PXuSIq5FoKtbevpKUoZB0qmmfvEDjH3r0HArrhIO8+T83H554XHUyyWlLu3Oz5mXcwgje1w+J0eU5TnSVN1Zg1cKIy99LfovzHG7i+06DYQLvBX6ApoVDwUn6exFCymSLA=,iv:7taN9nWhC9n5DEomlCuvvaukfGkC73RCaiSCwWbIzIs=,tag:hnN84UqINLCYD/1GU9vZ9A==,type:str]
    version: 3.13.2
