apiVersion: v1
kind: Secret
metadata:
    name: withings-app
    namespace: health
type: Opaque
stringData:
    WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:11+yaGnW2JF3qc6x1JampBjocAosuOMWKxtbuJHBnEs5RbR842ack6IqPllpAuxUcFlirxVa7z1bRwgwxXH1pA==,iv:9/IqH+eIBLZHe966GfrC7lpmN451lepvLefyDNtHIdw=,tag:/ElZdAlujbBsJZV3h4WnLQ==,type:str]
    WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:jmZ4I55sSFi/JhNorW1puNQ+7GOMpHsCnLk4WML2ym89HDFIAhZNomVyH2EQM9fLPbFeqLjCJWa1nK9/gLsSkQ==,iv:lPLfEB0P3CSk9omdG9h146BPZAD6wC+pVqfY8VkiX4Q=,tag:pKK0u2ssO+t4fgU4ImtV1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS3htNkJnVUxDcEVJc1Bu
            Q3JqajFTSEFnb3VZS1Y0Mm9tb0pHc09lNm1NCncrV1RIenNOQmd2VG1MNHFKN3pZ
            ZmtseERXRys4eWFuK3VZOE5odFMwVWcKLS0tIFg3dDc0ZDBoRHRjcEFBa2NRT2ds
            NWJWTXArV3czRmxmUHdBK1B6TWFWajgKfFHLS9ILMoQ6HJzJFvggZzrPu/dTnQEL
            3ENYyfqTNQqynsjExM/Ub16Gjblm3LEjgfQoLfHpKXTkj3GsH5S+tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T11:17:15Z"
    mac: ENC[AES256_GCM,data:ke5ZXK/5+NFwdS3XOIuxm2/RowCh4VnYnRcj+6oBnCq3RrRTZi1BnoC3hiFu8BqLYYMCleg4h3IYNlErVue6ohit12KFgF24fqQVz+ayKd9q/mE4kr06VB2X+nOszwq3KQp5Y2S9Eseoe0TEyQ2rdV97mP4d6ySnbjU52N8w7Es=,iv:0zRGDzhy+XJYh61q5vlKYooRhDrcQ6rC4FwiO2cuKIM=,tag:iOGij95B6sQl2Kl4opI6jQ==,type:str]
    version: 3.13.2
