apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tessarack-ingress
resources:
  - ../../base/tessarack-ingress/
  - tunnel-credentials.yaml
  - certificate.yaml
  - whoami.yaml
