apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:sJK1sW1j4//iBOUZDMjkr2KYGSl1EOujYToO5d4lj8MIJCCB3ataFVeH0nl5SL4KMYcnoMrh35yDidYvA9a3+ASD/uZbvQyh04m9lx9uC/1fKJQ+Z3Lyp1GR3ISs3fngu2xZ0OwsXAIvcA1GNKlVmBZ7Z2qFJmfIAAJKeMwZBci+q56iGgXmDSbqpgE5t36bjUPq6pzyLNqgYpL0I9Mi1+Zm/LuOOPgJatW5wuJeqcuu64T5HcTRsYXaxP7FSOfEk+fy+u1slHDGdRDfxIHWmRJBv3UO59HH043pKcj+NY183d68vUuFYWbI4gM=,iv:0LD+ODuETOOymrBN1eGq8dlsTRb1ootBqXS6SlTWZcg=,tag:6gjX5LgJSx6z8+2zmdrFMQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: tessarack-ingress
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdGp5NENiNks5bkpzNFRh
            R0MxSmhQODljS2hoYlpVemRUSk1yZE9YcjA4Cmw3NE1MVmJWM3JhSnV6aG4wakhq
            dWQ5K0RTWUJ3UjgrU2pVbk5CV2lBc3cKLS0tIGViWUlGY1l0OXRJUEFHSEp6MTc4
            Q2dxOC9acTBiQWttS1YzeGZJdjRJbGcK3HL7Ln6TupbC9MC1UWyIs9dl8n0NfVVI
            z1cscThCkaRNia97dzYskZBrGtwsZzzbHt+DimxgO42pVYbtA+ysCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ss0hjwrz2rdz8xjxraw9htnrvj6x5sc0r8kkjygz360ete50mdas37ga70
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T10:45:52Z"
    mac: ENC[AES256_GCM,data:a3pRyhJBMyIdI9Xk5HT4hjJPfQZ9EkN9cahw72VFO2PpPXhIjwg/Wl2/S9sDjkIoMf/eOERcYxBSGOYx0ynZ7d1DbmryeLeYf15eVALC2xBAGGof8tCtlLmIg1gLaTSx9KIo8vnOYuBivzllYrVdxUI2cjtErTzEIuPrp7XlM/Y=,iv:iFiSpZI3P6y2DpaTm3oig9pXm9w4nGsstyf91Aq5RPQ=,tag:HSi/NTJ7RDqzPZSaVtlyig==,type:str]
    version: 3.13.2
